//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 6/09/10 6:23:17 PM
namespace ThiNgeModel
{
    
    /// <summary>
    /// There are no comments for ThiNgeEntities in the schema.
    /// </summary>
    public partial class ThiNgeEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new ThiNgeEntities object using the connection string found in the 'ThiNgeEntities' section of the application configuration file.
        /// </summary>
        public ThiNgeEntities() : 
                base("name=ThiNgeEntities", "ThiNgeEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new ThiNgeEntities object.
        /// </summary>
        public ThiNgeEntities(string connectionString) : 
                base(connectionString, "ThiNgeEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new ThiNgeEntities object.
        /// </summary>
        public ThiNgeEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "ThiNgeEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Config in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Config> Config
        {
            get
            {
                if ((this._Config == null))
                {
                    this._Config = base.CreateQuery<Config>("[Config]");
                }
                return this._Config;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Config> _Config;
        /// <summary>
        /// There are no comments for Config in the schema.
        /// </summary>
        public void AddToConfig(Config config)
        {
            base.AddObject("Config", config);
        }
    }
    /// <summary>
    /// There are no comments for ThiNgeModel.Config in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ConfigID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ThiNgeModel", Name="Config")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Config : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Config object.
        /// </summary>
        /// <param name="configID">Initial value of ConfigID.</param>
        public static Config CreateConfig(int configID)
        {
            Config config = new Config();
            config.ConfigID = configID;
            return config;
        }
        /// <summary>
        /// There are no comments for Property ConfigID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ConfigID
        {
            get
            {
                return this._ConfigID;
            }
            set
            {
                this.OnConfigIDChanging(value);
                this.ReportPropertyChanging("ConfigID");
                this._ConfigID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ConfigID");
                this.OnConfigIDChanged();
            }
        }
        private int _ConfigID;
        partial void OnConfigIDChanging(int value);
        partial void OnConfigIDChanged();
        /// <summary>
        /// There are no comments for Property CheckMac in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> CheckMac
        {
            get
            {
                return this._CheckMac;
            }
            set
            {
                this.OnCheckMacChanging(value);
                this.ReportPropertyChanging("CheckMac");
                this._CheckMac = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CheckMac");
                this.OnCheckMacChanged();
            }
        }
        private global::System.Nullable<bool> _CheckMac;
        partial void OnCheckMacChanging(global::System.Nullable<bool> value);
        partial void OnCheckMacChanged();
        /// <summary>
        /// There are no comments for Property ChoLoginWeb in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> ChoLoginWeb
        {
            get
            {
                return this._ChoLoginWeb;
            }
            set
            {
                this.OnChoLoginWebChanging(value);
                this.ReportPropertyChanging("ChoLoginWeb");
                this._ChoLoginWeb = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ChoLoginWeb");
                this.OnChoLoginWebChanged();
            }
        }
        private global::System.Nullable<bool> _ChoLoginWeb;
        partial void OnChoLoginWebChanging(global::System.Nullable<bool> value);
        partial void OnChoLoginWebChanged();
        /// <summary>
        /// There are no comments for Property HienThiThongBaoTrenWeb in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> HienThiThongBaoTrenWeb
        {
            get
            {
                return this._HienThiThongBaoTrenWeb;
            }
            set
            {
                this.OnHienThiThongBaoTrenWebChanging(value);
                this.ReportPropertyChanging("HienThiThongBaoTrenWeb");
                this._HienThiThongBaoTrenWeb = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("HienThiThongBaoTrenWeb");
                this.OnHienThiThongBaoTrenWebChanged();
            }
        }
        private global::System.Nullable<bool> _HienThiThongBaoTrenWeb;
        partial void OnHienThiThongBaoTrenWebChanging(global::System.Nullable<bool> value);
        partial void OnHienThiThongBaoTrenWebChanged();
        /// <summary>
        /// There are no comments for Property NoiDungThongBaoTrenWeb in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string NoiDungThongBaoTrenWeb
        {
            get
            {
                return this._NoiDungThongBaoTrenWeb;
            }
            set
            {
                this.OnNoiDungThongBaoTrenWebChanging(value);
                this.ReportPropertyChanging("NoiDungThongBaoTrenWeb");
                this._NoiDungThongBaoTrenWeb = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("NoiDungThongBaoTrenWeb");
                this.OnNoiDungThongBaoTrenWebChanged();
            }
        }
        private string _NoiDungThongBaoTrenWeb;
        partial void OnNoiDungThongBaoTrenWebChanging(string value);
        partial void OnNoiDungThongBaoTrenWebChanged();
        /// <summary>
        /// There are no comments for Property ChoCacTruongGuiDanhSach in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> ChoCacTruongGuiDanhSach
        {
            get
            {
                return this._ChoCacTruongGuiDanhSach;
            }
            set
            {
                this.OnChoCacTruongGuiDanhSachChanging(value);
                this.ReportPropertyChanging("ChoCacTruongGuiDanhSach");
                this._ChoCacTruongGuiDanhSach = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ChoCacTruongGuiDanhSach");
                this.OnChoCacTruongGuiDanhSachChanged();
            }
        }
        private global::System.Nullable<bool> _ChoCacTruongGuiDanhSach;
        partial void OnChoCacTruongGuiDanhSachChanging(global::System.Nullable<bool> value);
        partial void OnChoCacTruongGuiDanhSachChanged();
        /// <summary>
        /// There are no comments for Property ChoCacTruongNhanDanhSach in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> ChoCacTruongNhanDanhSach
        {
            get
            {
                return this._ChoCacTruongNhanDanhSach;
            }
            set
            {
                this.OnChoCacTruongNhanDanhSachChanging(value);
                this.ReportPropertyChanging("ChoCacTruongNhanDanhSach");
                this._ChoCacTruongNhanDanhSach = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ChoCacTruongNhanDanhSach");
                this.OnChoCacTruongNhanDanhSachChanged();
            }
        }
        private global::System.Nullable<bool> _ChoCacTruongNhanDanhSach;
        partial void OnChoCacTruongNhanDanhSachChanging(global::System.Nullable<bool> value);
        partial void OnChoCacTruongNhanDanhSachChanged();
        /// <summary>
        /// There are no comments for Property ChoHoiDongThiNhanDanhSach in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> ChoHoiDongThiNhanDanhSach
        {
            get
            {
                return this._ChoHoiDongThiNhanDanhSach;
            }
            set
            {
                this.OnChoHoiDongThiNhanDanhSachChanging(value);
                this.ReportPropertyChanging("ChoHoiDongThiNhanDanhSach");
                this._ChoHoiDongThiNhanDanhSach = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ChoHoiDongThiNhanDanhSach");
                this.OnChoHoiDongThiNhanDanhSachChanged();
            }
        }
        private global::System.Nullable<bool> _ChoHoiDongThiNhanDanhSach;
        partial void OnChoHoiDongThiNhanDanhSachChanging(global::System.Nullable<bool> value);
        partial void OnChoHoiDongThiNhanDanhSachChanged();
        /// <summary>
        /// There are no comments for Property ChoCacTruongNhanKetQua in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> ChoCacTruongNhanKetQua
        {
            get
            {
                return this._ChoCacTruongNhanKetQua;
            }
            set
            {
                this.OnChoCacTruongNhanKetQuaChanging(value);
                this.ReportPropertyChanging("ChoCacTruongNhanKetQua");
                this._ChoCacTruongNhanKetQua = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ChoCacTruongNhanKetQua");
                this.OnChoCacTruongNhanKetQuaChanged();
            }
        }
        private global::System.Nullable<bool> _ChoCacTruongNhanKetQua;
        partial void OnChoCacTruongNhanKetQuaChanging(global::System.Nullable<bool> value);
        partial void OnChoCacTruongNhanKetQuaChanged();
        /// <summary>
        /// There are no comments for Property ChoHoiDongNhanKetQua in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> ChoHoiDongNhanKetQua
        {
            get
            {
                return this._ChoHoiDongNhanKetQua;
            }
            set
            {
                this.OnChoHoiDongNhanKetQuaChanging(value);
                this.ReportPropertyChanging("ChoHoiDongNhanKetQua");
                this._ChoHoiDongNhanKetQua = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ChoHoiDongNhanKetQua");
                this.OnChoHoiDongNhanKetQuaChanged();
            }
        }
        private global::System.Nullable<bool> _ChoHoiDongNhanKetQua;
        partial void OnChoHoiDongNhanKetQuaChanging(global::System.Nullable<bool> value);
        partial void OnChoHoiDongNhanKetQuaChanged();
        /// <summary>
        /// There are no comments for Property ChoThuKyNhapDiem in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> ChoThuKyNhapDiem
        {
            get
            {
                return this._ChoThuKyNhapDiem;
            }
            set
            {
                this.OnChoThuKyNhapDiemChanging(value);
                this.ReportPropertyChanging("ChoThuKyNhapDiem");
                this._ChoThuKyNhapDiem = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ChoThuKyNhapDiem");
                this.OnChoThuKyNhapDiemChanged();
            }
        }
        private global::System.Nullable<bool> _ChoThuKyNhapDiem;
        partial void OnChoThuKyNhapDiemChanging(global::System.Nullable<bool> value);
        partial void OnChoThuKyNhapDiemChanged();
        /// <summary>
        /// There are no comments for Property ChoThuKyQuayLaiKhiNhapDiem in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> ChoThuKyQuayLaiKhiNhapDiem
        {
            get
            {
                return this._ChoThuKyQuayLaiKhiNhapDiem;
            }
            set
            {
                this.OnChoThuKyQuayLaiKhiNhapDiemChanging(value);
                this.ReportPropertyChanging("ChoThuKyQuayLaiKhiNhapDiem");
                this._ChoThuKyQuayLaiKhiNhapDiem = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ChoThuKyQuayLaiKhiNhapDiem");
                this.OnChoThuKyQuayLaiKhiNhapDiemChanged();
            }
        }
        private global::System.Nullable<bool> _ChoThuKyQuayLaiKhiNhapDiem;
        partial void OnChoThuKyQuayLaiKhiNhapDiemChanging(global::System.Nullable<bool> value);
        partial void OnChoThuKyQuayLaiKhiNhapDiemChanged();
        /// <summary>
        /// There are no comments for Property KyThiHienTai in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> KyThiHienTai
        {
            get
            {
                return this._KyThiHienTai;
            }
            set
            {
                this.OnKyThiHienTaiChanging(value);
                this.ReportPropertyChanging("KyThiHienTai");
                this._KyThiHienTai = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("KyThiHienTai");
                this.OnKyThiHienTaiChanged();
            }
        }
        private global::System.Nullable<int> _KyThiHienTai;
        partial void OnKyThiHienTaiChanging(global::System.Nullable<int> value);
        partial void OnKyThiHienTaiChanged();
    }
}
